Testing

diff --git a/0x00-python-hello_world/101-compile b/0x00-python-hello_world/101-compile
--- a/0x00-python-hello_world/101-compile
+++ b/0x00-python-hello_world/101-compile
@@ -1,8 +1,8 @@
 #!/bin/bash
 
 if [[ -z "$PYFILE" ]] then
-  echo "Error: PYFILE environment variable not set."
-  exit 1
+        echo "Error: PYFILE environment variable not set."
+        exit 1
 fi
 
 # Compile the Python script
@@ -10,11 +10,10 @@ python3 -m py_compile "$PYFILE"
 
 # Check if compilation was successful
 if [[ $? -eq 0 ]] then
-  compiled_file="${PYFILE}c"
-  echo "Compiling $PYFILE ..."
-  mv "__pycache__/$compiled_file" "$compiled_file"
-  echo "Compilation successful."
+        echo "Compiling $PYFILE ..."
+        mv "__pycache__/$PYFILE.cpython-*.pyc" "$PYFILEc"
+        echo "Compilation successful."
 else
-  echo "Compilation failed."
+        echo "Compilation failed."
 fi
 
